("king" - "man" + "woman", "queen")
("skateboard" - "wheels", "snowboard")
("whiteboard" - "white" + "black", "blackboard")
("cup" + "coffee", "mug")
("whale" - "mammal", "fish")
("monkey" + "intelligence", "human")
("city" + "eiffel tower", "paris")
("vehicle" + "bed", "truck")
("home" + "wheels", "rv")
("sleep" + "travel", "hotel")
("sleep" + "travel" + "car", "motel")
("shirt" - "sleeves", "tank top")
("shirt" + "hat", "hoodie")
("sky" + "water", "rain")
("ground" + "shake", "earthquake")
("cloud" + "lightning", "storm")
("clock" + "wrist", "watch")
("pickle" - "vinegar", "cucumber")
("computer" + "mobile", "laptop")
("music" + "loud" + "outside", "concert")
("priest" - "catholic" + "islam", "imam")
("bird" + "walks" + "large", "ostrich")